# Default plugin configuration

# Global defaults and settings
blacklist-default:
  - CHEST
cooldown-default: 0

# Region-related defaults
default-region-size: 5
blacklisted-blocks:
  - LAVA
  - CACTUS
