name: ParkourRegion
version: 1.0.0
main: com.example.parkourregion.ParkourRegion
api-version: 1.21
author: AbdullahWajahat
commands:
  por:
    description: Main ParkourRegion command
    usage: /por <subcommand>
    permission: parkourregion.admin
permissions:
  parkourregion.admin:
    description: Full access to all ParkourRegion commands
    default: op
