name: ParkourManager
main: com.example.parkourmanager.ParkourManager
version: 1.21.8
api-version: 1.19
author: YourName
description: A powerful parkour region manager plugin.
website: https://yourwebsite.com

commands:
  parkourmanager:
    description: Main command for Parkour Manager
    usage: /<command> help
    aliases: [pm]
    permission: parkourmanager.use

permissions:
  parkourmanager.use:
    description: Allows usage of Parkour Manager commands
    default: op

  parkourmanager.admin:
    description: Full access to all parkour commands
    default: op
