name: ParkourRegion
version: 2.0
main: com.example.parkourregion.ParkourRegion
api-version: 1.21
permissions:
  parkourregion.admin:
    description: Allows managing parkour regions
    default: op
commands:
  por:
    description: Main parkour command
    usage: /<command> <args>
