# File: src/main/resources/plugin.yml
name: ParkourRegion
version: 1.0.0
main: com.example.parkourregion.ParkourRegionPlugin
api-version: 1.20
commands:
  por:
    description: Main parkour command
    usage: /por <subcommand>
    aliases: []
    permission: parkourregion.use
    permission-message: "&cYou do not have permission to use this command."
