name: ParkourManager
main: com.example.parkourmanager.ParkourManager
version: 1.0.0
api-version: 1.21
authors: [ "YourName" ]
description: Parkour Manager plugin with regions, checkpoints, blacklist blocks, cooldowns, and more.
commands:
  parkourmanager:
    description: Main Parkour Manager command
    aliases: [pm]
    usage: /<command>
    permission: parkourmanager.use
permissions:
  parkourmanager.use:
    description: Allows use of Parkour Manager commands
    default: op
